server:
  port: 9002
  
spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
    
service-registry:
  eureka:
    url:
      department-service: http://DEPARTMENT-SERVICE/departments/
