server:
  port: 8104
  
spring:
  application:
    name: USER-SERVICE
  datasource:
#    url: jdbc:h2:mem:${spring.application.name} #IN-MEMORY DB
    url: jdbc:h2:file:C:/h2db/db-files/${spring.application.name}.h2db #FILESYSTEM DB PERSISTED
    driverClassName: org.h2.Driver
    username: ${spring.application.name}
    password: ${spring.application.name}@${server.port}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

service-registry:
  eureka:
    url:
      department-service: http://DEPARTMENT-SERVICE/departments/                  # URL behind CLOUD-API-GATEWAY
      messaging-rabbitmq-producer: http://MSG-RABBITMQ-PRODUCER/mq/rabbitmq/publish/  # URL behind CLOUD-API-GATEWAY
