--select ID, FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID from user
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Jérôme', 'AROME', 'jerome.arome@corp.ch');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('David', 'EGOLIATH', 'David.EGOLIATH@bluewin.ch');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Skool', 'KARMA', 'Skool.KARMA@noob.com');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Nelson', 'MENFIN', 'Nelson.MENFIN@isport.org');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Rachida', 'PADI', 'Rachida.PADI@gnu.com');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('GERARD', 'MENFIN', 'GERARD.MENFIN@asco.net');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('ALAIN', 'TERIEUR', 'ALAIN.TERIEUR@member.co');
