--select ID, FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID from user
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) VALUES ('Jérôme', 'AROME', 'jerome.arome@corp.ch', 1);
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) VALUES ('David', 'EGOLIATH', 'David.EGOLIATH@bluewin.ch', 1);
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) VALUES ('Skool', 'KARMA', 'Skool.KARMA@noob.com', 1);
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) VALUES ('Nelson', 'MENFIN', 'Nelson.MENFIN@isport.org', 1);
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) VALUES ('Rachida', 'PADI', 'Rachida.PADI@gnu.com', 1);
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) VALUES ('GERARD', 'MENFIN', 'GERARD.MENFIN@asco.net', 1);
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) VALUES ('ALAIN', 'TERIEUR', 'ALAIN.TERIEUR@member.co', 1);
