server:
  port: 8501
  
spring:
  application:
    name: MSG-RABBITMQ-PRODUCER
  rabbitmq:    addresses: localhost:5672 #This is the default address of RabbitMQ Server (optional when default!!)
