--select ID, NAME, ADDRESS, CODE from department
INSERT INTO DEPARTMENT (NAME, ADDRESS, CODE) VALUES ('Contrat', 'Parc Avenue 1001', '1925');
INSERT INTO DEPARTMENT (NAME, ADDRESS, CODE) VALUES ('Sinistre', 'Marc Avenue 25', '57540');
INSERT INTO DEPARTMENT (NAME, ADDRESS, CODE) VALUES ('Finance', '21 Jump Street', '42744');
INSERT INTO DEPARTMENT (NAME, ADDRESS, CODE) VALUES ('Invoicing', 'Street Food 42', '3415');
INSERT INTO DEPARTMENT (NAME, ADDRESS, CODE) VALUES ('Sales', 'Street Art 321', '9853');
INSERT INTO DEPARTMENT (NAME, ADDRESS, CODE) VALUES ('Marketing', 'Central Road', '8872');
INSERT INTO DEPARTMENT (NAME, ADDRESS, CODE) VALUES ('Tech', 'Road 66', '12744');
