server:
  port: 8101
  
spring:  application:    name: CLOUD-API-GATEWAY
  cloud:    gateway:      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        filters:
        - name: CircuitBreaker
          args:
            name: USER-SERVICE
            fallbackuri: forward:/userServiceFallBack
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/departments/**
        filters:
        - name: CircuitBreaker
          args:
            name: DEPARTMENT-SERVICE
            fallbackuri: forward:/departmentServiceFallBack
      - id: MSG-RABBITMQ-PRODUCER
        uri: lb://MSG-RABBITMQ-PRODUCER
        predicates:
        - Path=/mq/rabbitmq/publish/**
        filters:
        - name: CircuitBreaker
          args:
            name: MSG-RABBITMQ-PRODUCER
            fallbackuri: forward:/rabbitmqProducerFallBack
      - id: MSG-KAFKA-PRODUCER
        uri: lb://MSG-KAFKA-PRODUCER
        predicates:
        - Path=/messaging/kafka/**
        filters:
        - name: CircuitBreaker
          args:
            name: MSG-KAFKA-PRODUCER
            fallbackuri: forward:/kafkaProducerFallBack

# currently no routeId for messaging-kafka-consumer (MSG-KAFKA-CONSUMER) because not a web module
hystrix:  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
      
management:
  endpoints:    web:      exposure:        include: hystrix.stream

