server:
  port: 8100
  
spring:  application:    name: CLOUD-CONFIG-SERVER  cloud:    config:      server:        git:          uri: https://github.com/karmaskool/karmatech.git
          default-label: develop
          basedir: /data/cloud-config-server/git
          force-pull: false
          search-paths:          - com/impact/karma/demo/config/config-server
          clone-on-start: true
