server:
  port: 8507
  
spring:
  application:
    name: MSG-ACTIVEMQ-ARTEMIS-PRODUCER
  # Embedded ActiveMQ Configuration Example
  activemq:
#     broker.url: tcp://localhost:61616 #This is the default tcp address of ActiveMQ Server; @see <transportConnector> in apache-activemq-5.x.y/conf/activemq.xml
      broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
      in-memory: true
      non-blocking-redelivery: true
      packages:
        trust-all: false
        trusted: com.memorynotfound
      pool:
        block-if-full: true
        block-if-full-timeout: -1
#        create-connection-on-startup: true deprecated
        enabled: false
#        expiry-timeout: 0 deprecated
        idle-timeout: 30000
        max-connections: 1
        max-sessions-per-connection: 500
#        reconnect-on-exception: true
        time-between-expiration-check: -1
        use-anonymous-producers: true

  # Spring JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non-persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000

destination:
  order: karma-queue
  