server:
  port: 8502
  
spring:
  application:
    name: MSG-RABBITMQ-CONSUMER
  rabbitmq:    addresses: localhost:5672 #This is the default address of RabbitMQ Server (optional whendefault!!)
