server:
   port: 8601

spring:
  application:
    name: DATA-SQL-MYSQL-CRUD
  jpa:
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
              ddl-auto: create
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      show-sql: true
  properties:
      hibernate:
          jdbc:
              lob:
                  non_contextual_creation: true

#<dependency>
#  <groupId>org.postgresql</groupId>
#  <artifactId>postgresql</artifactId>
#  <scope>runtime</scope>
#</dependency>
